name: Update Signatures

on:
  repository_dispatch:  # Trigger this action via a repository dispatch event
    types: [add-signature]  # Custom event name

jobs:
  update-signature:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update signatures.json
      run: |
        # Install jq to handle JSON data
        sudo apt-get install jq

        # Path to the signatures file
        FILE_PATH="signatures.json"
        SIGNATURE="{
          \"name\": \"${{ github.event.client_payload.username }}\",
          \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
        }"

        # Get the current content of the file
        CURRENT_CONTENT=$(cat $FILE_PATH)

        # Add the new signature to the file
        UPDATED_CONTENT=$(echo "$CURRENT_CONTENT" | jq ". + [$SIGNATURE]")

        # Update the file on GitHub
        echo "$UPDATED_CONTENT" > $FILE_PATH

        # Commit the changes
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add $FILE_PATH
        git commit -m "Update signatures with new entry"
        git push
